version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/frankenphp.Dockerfile
    container_name: nuri-backend-app
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    networks:
      - nuri-net
    volumes:
      - ./:/app
    environment:
      APP_ENV: production
      APP_DEBUG: true
      APP_KEY: base64:tIibNdhAavArXMGOjl1Q+mqPTJ2KibURxgIs4Y7rWmw=
      APP_URL: https://prenava.web.id

      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: nuri_db
      DB_USERNAME: root
      DB_PASSWORD: 

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      REDIS_URL: "tcp://redis:6379"
      REDIS_DB: 0
      REDIS_CACHE_DB: 1

  mysql:
    image: mysql:8.0
    container_name: nuri-backend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nuri_db
      MYSQL_USER: nuri
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nuri-net
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: nuri-backend-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - nuri-net
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nuri-backend-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 
    depends_on:
      - mysql
    networks:
      - nuri-net
    ports:
      - "8081:80"

volumes:
  mysql_data:
  redis_data:
  caddy_data:
  caddy_config:

networks:
  nuri-net:
    driver: bridge
