services:
  app:
    build:
      context: .
      dockerfile: docker/frankenphp.Dockerfile
    container_name: nuri-backend-app
    restart: unless-stopped
    depends_on:
      - mysql
      - redis
    networks:
      - nuri-net
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/app               
      - ./.env:/app/.env  

  mysql:
    image: mysql:8.0
    container_name: nuri-backend-mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: nuri_db
      MYSQL_USER: nuri
      MYSQL_PASSWORD: 
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nuri-net
    ports:
      - "3307:3306"

  redis:
    image: redis:7-alpine
    container_name: nuri-backend-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    networks:
      - nuri-net
    volumes:
      - redis_data:/data

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: nuri-backend-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: 
    depends_on:
      - mysql
    networks:
      - nuri-net
    ports:
      - "8081:80"

volumes:
  mysql_data:
  redis_data:

networks:
  nuri-net:
    driver: bridge
